[cosmic-ray]
module-path = "mpu"
python-version = ""
timeout = 10
exclude-modules = []
test-command = "python3 -m pytest"
execution-engine.name = "local"

[cosmic-ray.cloning]
method = 'copy'
commands = []